language: swift
osx_image: xcode9
script:
  - xcodebuild -version
  - xcodebuild -project Jeu de Nim.xcodeproj -scheme iOSTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
  
